### ISSUE TITLE
Option to forfeit or delete game

### ISSUE THREAD

**Issue by xxhellokittyluvrxx** [rally-the-troops/server#2]
There is currently no way (that I can see) to delete a game or forfeit. This results in a game being stuck in a user's active games. A forfeit or delete button would be useful.

**Comment by ccxvii** [comment]
You can normally choose "Resign" in the cog-wheel menu. This option has been temporarily turned off for Shores of Tripoli for the duration of the current tournament.

Solo games can be deleted from the "join" page.
