### ISSUE TITLE
Pax Pamir

### ISSUE THREAD

**Issue by scottrbird** [rally-the-troops/server#3]
Didn't see a Pax Pamir repository... When I play AQB to my court, the special ability "Savvy Operator" says it should be treated like the favored suit.  Doesn't that mean I should be able to immediately use the Betray action on it as a bonus action?  Or am I reading the rules wrong?  Thanks.

**Comment by ccxvii** [comment]
It does, but other cards in your game prevent you from taking the bonus action.
